Add `@JvmOverloads` annotation to `loginSso`
A dependency is getting `java.lang.NoSuchMethodError` since they make the call without the new parameters. Apply `@JvmOverloads` so the compiler generates the relevant method signature.